/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AutoComplete: typeof import('./components/AutoComplete/index').AutoComplete
  const BUTTON_EFFECT_MAP: typeof import('./components/Button/types').BUTTON_EFFECT_MAP
  const BUTTON_SIZE_MAP: typeof import('./components/Button/types').BUTTON_SIZE_MAP
  const BUTTON_TYPE_MAP: typeof import('./components/Button/types').BUTTON_TYPE_MAP
  const BUTTON_TYPE_MAP_ACTIVE: typeof import('./components/Button/types').BUTTON_TYPE_MAP_ACTIVE
  const BUTTON_TYPE_MAP_BORDER: typeof import('./components/Button/types').BUTTON_TYPE_MAP_BORDER
  const BUTTON_TYPE_MAP_HOVER: typeof import('./components/Button/types').BUTTON_TYPE_MAP_HOVER
  const BUTTON_TYPE_MAP_TEXT: typeof import('./components/Button/types').BUTTON_TYPE_MAP_TEXT
  const BUTTON_VARIANT_MAP: typeof import('./components/Button/types').BUTTON_VARIANT_MAP
  const BUTTON_VARIANT_MAP_ACTIVE: typeof import('./components/Button/types').BUTTON_VARIANT_MAP_ACTIVE
  const BUTTON_VARIANT_MAP_BORDER: typeof import('./components/Button/types').BUTTON_VARIANT_MAP_BORDER
  const BUTTON_VARIANT_MAP_HOVER: typeof import('./components/Button/types').BUTTON_VARIANT_MAP_HOVER
  const BUTTON_VARIANT_MAP_TEXT: typeof import('./components/Button/types').BUTTON_VARIANT_MAP_TEXT
  const Button: typeof import('./components/Button/index').Button
  const Default: typeof import('./components/Popover/index.stories').Default
  const Form: typeof import('./components/Form/index').Form
  const ICON_VARIANT_MAP: typeof import('./components/Icon/types').ICON_VARIANT_MAP
  const INPUT_EFFECT_MAP: typeof import('./components/Input/types').INPUT_EFFECT_MAP
  const INPUT_SIZE_MAP: typeof import('./components/Input/types').INPUT_SIZE_MAP
  const Icon: typeof import('./components/Icon/index').Icon
  const Input: typeof import('./components/Input/index').Input
  const Item: typeof import('./components/Menu/verticalItem').Item
  const LIGHTER_BUTTON_BG: typeof import('./components/Button/types').LIGHTER_BUTTON_BG
  const Menu: typeof import('./components/Menu/index').Menu
  const Popover: typeof import('./components/Popover/index').Popover
  const buttonStories: typeof import('./components/Button/index.stories').default
  const context: typeof import('./components/Menu/index').context
  const horizontalItem: typeof import('./components/Menu/horizontalItem').default
  const iconStories: typeof import('./components/Icon/index.stories').default
  const indexStories: typeof import('./components/Popover/index.stories').default
  const item: typeof import('./components/Menu_副本/item').default
  const menuStories: typeof import('./components/Menu/index.stories').default
  const popoverStories: typeof import('./components/Popover/index.stories').default
  const sub: typeof import('./components/Menu/sub').default
  const verticalItem: typeof import('./components/Menu/verticalItem').default
}
// for type re-export
declare global {
  // @ts-ignore
  export type { autoCompleteProps } from './components/AutoComplete/types'
  import('./components/AutoComplete/types')
  // @ts-ignore
  export type { buttonVariant, buttonEffect, buttonSize, buttonProps } from './components/Button/types'
  import('./components/Button/types')
  // @ts-ignore
  export type { formProps } from './components/Form/types'
  import('./components/Form/types')
  // @ts-ignore
  export type { iconProps } from './components/Icon/types'
  import('./components/Icon/types')
  // @ts-ignore
  export type { inputSize, inputEffect, inputProps } from './components/Input/types'
  import('./components/Input/types')
  // @ts-ignore
  export type { menuMode, menuSize, item, menuItemProps, menuProps, contextType } from './components/Menu/types'
  import('./components/Menu/types')
  // @ts-ignore
  export type { triggerType, popoverProps } from './components/Popover/types'
  import('./components/Popover/types')
}
