/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AutoComplete: typeof import('./components/AutoComplete/index').AutoComplete
  const BUTTON_EFFECT_MAP: typeof import('./components/Button/types').BUTTON_EFFECT_MAP
  const BUTTON_SIZE_MAP: typeof import('./components/Button/types').BUTTON_SIZE_MAP
  const BUTTON_TYPE_MAP: typeof import('./components/Button/types').BUTTON_TYPE_MAP
  const BUTTON_TYPE_MAP_ACTIVE: typeof import('./components/Button/types').BUTTON_TYPE_MAP_ACTIVE
  const BUTTON_TYPE_MAP_BORDER: typeof import('./components/Button/types').BUTTON_TYPE_MAP_BORDER
  const BUTTON_TYPE_MAP_HOVER: typeof import('./components/Button/types').BUTTON_TYPE_MAP_HOVER
  const BUTTON_TYPE_MAP_TEXT: typeof import('./components/Button/types').BUTTON_TYPE_MAP_TEXT
  const BUTTON_VARIANT_MAP: typeof import('./components/Button/types').BUTTON_VARIANT_MAP
  const BUTTON_VARIANT_MAP_ACTIVE: typeof import('./components/Button/types').BUTTON_VARIANT_MAP_ACTIVE
  const BUTTON_VARIANT_MAP_BORDER: typeof import('./components/Button/types').BUTTON_VARIANT_MAP_BORDER
  const BUTTON_VARIANT_MAP_HOVER: typeof import('./components/Button/types').BUTTON_VARIANT_MAP_HOVER
  const BUTTON_VARIANT_MAP_TEXT: typeof import('./components/Button/types').BUTTON_VARIANT_MAP_TEXT
  const Button: typeof import('./components/Button/index').Button
  const CASCADER_SIZE_MAP: typeof import('./components/Cascader/types').CASCADER_SIZE_MAP
  const Cascader: typeof import('./components/Cascader/index').Cascader
  const Checkbox: typeof import('./components/Checkbox/index').Checkbox
  const DATEPICKER_SIZE_MAP: typeof import('./components/DatePicker/types').DATEPICKER_SIZE_MAP
  const DatePicker: typeof import('./components/DatePicker/index').DatePicker
  const Default: typeof import('./components/Popover/index.stories').Default
  const Form: typeof import('./components/Form/index').Form
  const ICON_VARIANT_MAP: typeof import('./components/Icon/types').ICON_VARIANT_MAP
  const INPUT_EFFECT_MAP: typeof import('./components/Input/types').INPUT_EFFECT_MAP
  const INPUT_SIZE_MAP: typeof import('./components/Input/types').INPUT_SIZE_MAP
  const Icon: typeof import('./components/Icon/index').Icon
  const Input: typeof import('./components/Input/index').Input
  const Item: typeof import('./components/Menu/verticalItem').Item
  const LIGHTER_BUTTON_BG: typeof import('./components/Button/types').LIGHTER_BUTTON_BG
  const MESSAGE_TYPE_MAP: typeof import('./components/Message/types').MESSAGE_TYPE_MAP
  const Menu: typeof import('./components/Menu/index').Menu
  const Message: typeof import('./components/Message/message').Message
  const Modal: typeof import('./components/Modal/index').Modal
  const PROGRESS_VARIANT_MAP: typeof import('./components/Progress/types').PROGRESS_VARIANT_MAP
  const Popover: typeof import('./components/Popover/index').Popover
  const Progress: typeof import('./components/Progress/index').Progress
  const Radio: typeof import('./components/Radio/index').Radio
  const SELECT_SIZE_MAP: typeof import('./components/Select/types').SELECT_SIZE_MAP
  const SWITCH_SIZE_MAP: typeof import('./components/Switch/types').SWITCH_SIZE_MAP
  const SWITCH_VARIANT_MAP: typeof import('./components/Switch/types').SWITCH_VARIANT_MAP
  const Select: typeof import('./components/Select/index').Select
  const Switch: typeof import('./components/Switch/index').Switch
  const Upload: typeof import('./components/Upload/index').Upload
  const buttonStories: typeof import('./components/Button/index.stories').default
  const context: typeof import('./components/Menu/index').context
  const dispatch: typeof import('./components/Form/useStore').dispatch
  const dragger: typeof import('./components/Upload/dragger').default
  const fields: typeof import('./components/Form/useStore').fields
  const form: typeof import('./components/Form/useStore').form
  const group: typeof import('./components/Radio/group').default
  const horizontalItem: typeof import('./components/Menu/horizontalItem').default
  const iconStories: typeof import('./components/Icon/index.stories').default
  const indexStories: typeof import('./components/Popover/index.stories').default
  const item: typeof import('./components/Menu_副本/item').default
  const menu: typeof import('./components/Cascader/menu').default
  const menuStories: typeof import('./components/Menu/index.stories').default
  const message: typeof import('./components/Message/message').default
  const panel: typeof import('./components/DatePicker/panel').default
  const pannel: typeof import('./components/DatePickerbak/pannel').default
  const popoverStories: typeof import('./components/Popover/index.stories').default
  const range: typeof import('./components/DatePicker/range').default
  const sub: typeof import('./components/Menu/sub').default
  const upload: typeof import('./components/Upload/index').upload
  const useForm: typeof import('./components/Form/useForm').useForm
  const useStore: typeof import('./components/Form/useStore').default
  const verticalItem: typeof import('./components/Menu/verticalItem').default
}
// for type re-export
declare global {
  // @ts-ignore
  export type { autoCompleteProps } from './components/AutoComplete/types'
  import('./components/AutoComplete/types')
  // @ts-ignore
  export type { buttonVariant, buttonEffect, buttonSize, buttonProps } from './components/Button/types'
  import('./components/Button/types')
  // @ts-ignore
  export type { cascaderOption, cascaderSize, cascaderContext, cascaderProps, cascaderMenuProps } from './components/Cascader/types'
  import('./components/Cascader/types')
  // @ts-ignore
  export type { checkboxProps } from './components/Checkbox/types'
  import('./components/Checkbox/types')
  // @ts-ignore
  export type { datePickerSize, datePickerProps, rangeProps, panelProps } from './components/DatePicker/types'
  import('./components/DatePicker/types')
  // @ts-ignore
  export type { RenderProps, formLayout, formRules, formProps, itemProps, formContext } from './components/Form/types'
  import('./components/Form/types')
  // @ts-ignore
  export type { CustomRuleFuncParams, CustomRuleFunc, CustomRule, FieldDetail, FieldsState, ValidateErrorType, FormState, FieldsAction } from './components/Form/useStore'
  import('./components/Form/useStore')
  // @ts-ignore
  export type { iconProps } from './components/Icon/types'
  import('./components/Icon/types')
  // @ts-ignore
  export type { inputSize, inputEffect, inputProps } from './components/Input/types'
  import('./components/Input/types')
  // @ts-ignore
  export type { menuMode, menuSize, item, menuItemProps, menuProps, contextType } from './components/Menu/types'
  import('./components/Menu/types')
  // @ts-ignore
  export type { messageType, messageConfig, messageCall } from './components/Message/types'
  import('./components/Message/types')
  // @ts-ignore
  export type { modalProps } from './components/Modal/types'
  import('./components/Modal/types')
  // @ts-ignore
  export type { triggerType, popoverProps } from './components/Popover/types'
  import('./components/Popover/types')
  // @ts-ignore
  export type { progressVariant, progressProps } from './components/Progress/types'
  import('./components/Progress/types')
  // @ts-ignore
  export type { radioProps, groupLayout, groupOptions, groupProps } from './components/Radio/types'
  import('./components/Radio/types')
  // @ts-ignore
  export type { selectOptions, selectSize, selectProps } from './components/Select/types'
  import('./components/Select/types')
  // @ts-ignore
  export type { switchSize, switchVariant, switchProps } from './components/Switch/types'
  import('./components/Switch/types')
  // @ts-ignore
  export type { listType, uploadFileType, uploadFileStatus, uploadFile, uploadProps, draggerProps } from './components/Upload/types'
  import('./components/Upload/types')
}
